name: push-and-prs-on-main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Switch to Xcode 15.0
      run: sudo xcode-select -s "/Applications/Xcode_15.0.app"
    - name: Build iOS / macOS
      run: xcodebuild -verbose -scheme SiteApp -destination "generic/platform=iOS Simulator" -destination "generic/platform=macOS"
