name: push-and-prs-on-main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: sw_vers
      run: sw_vers
    - name: Switch to Xcode 16.4
      run: sudo xcode-select -s "/Applications/Xcode_16.4.app"
    - name: Show SDKs
      run: xcodebuild -showsdks
    - name: Build iOS / macOS / tvOS
      run: xcodebuild -verbose -skipPackagePluginValidation -scheme SiteApp -destination "generic/platform=iOS Simulator" -destination "generic/platform=macOS" -destination "generic/platform=tvOS Simulator"
